site_name: Smart Systems
theme:
  feature:
    tabs: true
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'orange'
  logo: 'assets/images/hanze.png'
  favicon: 'assets/images/ja.png'
markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - meta
nav:
  - Materials: 
    - Intro: 'index.md'
    - Demo: 'new.md'
  - Courses:
    - Micro Python: 'course/test.md'
    - Raspberry Pi: 'course/raspberry.md'
    - Raspberry Pi2: 'course/test2.md'
  - Labs:
    - Intro AI: 'test.md'
    - Robotics: 'test.md'
  - Research:
    - Remote Lab: 'test.md'

 



